# prometheus-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: server-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: my-prometheus-image:latest  # Dein gebautes Docker-Image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: server-ns
spec:
  type: NodePort # oder LoadBalancer, abhängig von deinem Setup
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30000 # z.B. einen festen Port auf dem Hostsystem
  selector:
    app: prometheus