apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
  namespace: server-ns
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pcaveman/projects/log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  namespace: server-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: server-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mio-server
  template:
    metadata:
      labels:
        app: mio-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: mio-server
        image: my-server-image:latest # nginx:latest # my-server-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8181
          name: message-port
        - containerPort: 8000
          name: metrics-port
        volumeMounts:
        - mountPath: /var/log/server
          name: log-storage
      volumes:
      - name: log-storage
        persistentVolumeClaim:
          claimName: log-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: server-ns
spec:
  type: ClusterIP
  selector:
    app: mio-server
  ports:
    - name: tcp-8181
      protocol: TCP
      port: 8181          # Porta esterna del servizio
      targetPort: 8181    # Porta del container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: server-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mio-client
  template:
    metadata:
      labels:
        app: mio-client
    spec:
      containers:
      - name: mio-client
        image: my-client-image:latest # nginx:latest # my-server-image:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/log/client
          name: log-storage
      volumes:
      - name: log-storage
        persistentVolumeClaim:
          claimName: log-pvc