apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
  namespace: server-ns
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pcaveman/projects/log