apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  namespace: server-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual