apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.serverApp }}
  ports:
    - name: {{ .Values.service.port.name }}
      protocol: {{ .Values.service.port.protocol }}
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.service.port.targetPort }}