apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serverName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.serverReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.serverApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.serverApp }}
        annotations:
          prometheus.io/scrape: {{ .Values.prometheusScrape }}
          prometheus.io/port: {{ .Values.prometheusContainerPort }}
    spec:
      containers:
        - name: {{ .Values.serverApp }}
          image: {{ .Values.serverImage.repository }}:{{ .Values.serverImage.tag }}
          imagePullPolicy: {{ .Values.serverImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: {{ .Values.messagePortName }}
            - containerPort: {{ .Values.prometheusContainerPort }}
              name: {{ .Values.metricsPortName }}
          volumeMounts:
            - mountPath: {{ .Values.serverVolumeMount.mountPath }}
              name: {{ .Values.volume.name }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.pvcName }}