apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-dst-rule
  namespace: server-ns
spec:
  host: server-service
  trafficPolicy:
    tls:
      mode: DISABLE
---